services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: postgres
    hostname: postgres
    volumes:
      - ./myvalume:/myvalume
    secrets:
      - postgres_pwd
    env_file:
      - .env
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    volumes:
      - ./pgadmin:/pgadmin
    secrets: 
      - pgadmin_pwd
    env_file:
      - .env
    restart: always
    ports:
      - "8000:80"

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    hostname: jupyter
    volumes:
      - ./myvalume:/myvalume
    secrets:
      - jupyter_token
      - postgres_pwd
    env_file:
      - .env
    ports:
      - "8888:${JUPYTER_PORT}"

secrets:
  postgres_pwd:
    file: ./secrets/postgres_pwd.txt
  pgadmin_pwd:
    file: ./secrets/pgadmin_pwd.txt
  jupyter_token:
    file: ./secrets/jupyter_token.txt
