FROM python:3.9.22-slim-bullseye

RUN pip install jupyterlab psycopg2-binary numpy pandas matplotlib scikit-learn seaborn statsmodels

CMD jupyter lab --ip=0.0.0.0 --port=$JUPYTER_PORT --allow-root --NotebookApp.token=$(cat $JUPYTER_TOKEN)
